### ISSUE TITLE
metadata customisation inserts nonunique entries.

### ISSUE THREAD

**Issue by brucellino** [AAROC/DevOps#185]
# Problem  description
the `metadata.yml` tasks of the `shibboleth-idp` role should apply several "lineinfiles" to the idp metadata in order to insert the organisation and contact information. This is done, however is repeated every run - ie, not idempotent. 

The process is carried out with several  tasks similar to:
```
- name: Open Organization stanza to metadata
  lineinfile:
    dest: "{{ shibboleth_install_path }}/metadata/idp-metadata.xml"
    insertbefore: "</EntityDescriptor>"
    regexp: "^<Organization>"
    line: "<Organization>"
    state: present
```

note the regexp. This is clearly not being caught for other stanzas such as : 
```
- name: Add Organisation URL
  lineinfile:
    regexp: "^<OrganizationURL>."
    dest: "{{ shibboleth_install_path }}/metadata/idp-metadata.xml"
    insertbefore: "</EntityDescriptor>"
    line: "<OrganizationURL xml:lang=\"en\">{{ host_institute.url }}</OrganizationURL>"
    state: present
```

# References

  1. http://docs.ansible.com/lineinfile_module.html
  1. http://stackoverflow.com/questions/19390600/ansible-lineinfile-duplicates-line
