### ISSUE TITLE
Java Error in liferay-csgf.yml

### ISSUE THREAD

**Issue by Abdelrahman-Hasan** [AAROC/DevOps#203]
Hi all,
i become the following error

```
failed: [sgw.asrenorg.net] => {"ansible_job_id": "554021991969.24545", "changed": true, "cmd": "./asadmin --interactive false --passwordfile /home/liferayadmin/passwordfile --user liferayadmin start-domain liferay", "delta": "0:00:01.036717", "end": "2015-03-23 08:18:47.607684", "finished": 1, "rc": 1, "start": "2015-03-23 08:18:46.570967", "warnings": []}
stderr: JVM failed to start: com.sun.enterprise.admin.launcher.GFLauncherException: The server exited prematurely with exit code 1.
Before it died, it produced the following output:
stdout: Command start-domain failed.
<job 554021991969.24545> FAILED on sgw.asrenorg.net

FATAL: all hosts have already failed -- aborting
```
@brucellino 
@fmarco76

**Comment by Abdelrahman1985** [comment]
after a new execution for this file i have the following error


TASK: [liferay-csgf | Start the Liferay Domain] *******************************
failed: [sgw.asrenorg.net] => {"ansible_job_id": "139731600538.18775", "changed": true, "cmd": "./asadmin --interactive false --passwordfile /etc/abd/passwordfile --user liferayadmin start-domain liferay", "delta": "0:00:01.071887", "end": "2015-03-23 11:40:42.335911", "finished": 1, "rc": 1, "start": "2015-03-23 11:40:41.264024", "warnings": []}
stderr: The Master Password is required to start the domain.  No console, no prompting possible.  You should either create the domain with --savemasterpassword=true or provide a password file with the --passwordfile option.
stdout: Command start-domain failed.
<job 139731600538.18775> FAILED on sgw.asrenorg.net

**Comment by brucellino** [comment]
this looks like a problem with glassfish itself. @fmarco76 can you remind us where these logs are ?

**Comment by Abdelrahman1985** [comment]
failed: [sgw.asrenorg.net] => {"ansible_job_id": "796803850166.22786", "changed": true, "cmd": "./asadmin --interactive false --passwordfile /home/liferayadmin/passwordfile --user liferayadmin start-domain liferay", "delta": "0:00:01.040719", "end": "2015-03-23 12:39:26.758936", "finished": 1, "rc": 1, "start": "2015-03-23 12:39:25.718217", "warnings": []}
stderr: Error starting domain liferay.
The server exited prematurely with exit code 1.
Before it died, it produced the following output:

Invalid initial heap size: -Xms
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
stdout: Waiting for liferay to start Command start-domain failed.
<job 796803850166.22786> FAILED on sgw.asrenorg.net

FATAL: all hosts have already failed -- aborting

**Comment by fmarco76** [comment]
It seems a problem with the password file.
The command executed by ansible refers to /etc/abd/passwordfile  but the task we develop was using a different file. Have you modified the file or performed other changes to justify the different file?

**Comment by brucellino** [comment]
ah ok. You're probably missing the `host_vars` that define the heap size. In our dev instance, we have 
```
min_jvm_size=1024m max_jvm_size=1024m db-server=vm03.ct.infn.it needs_certificate="false"
`
Those variables need to be defined (and the ones used are the bare minimum ones, you should choose higher values).
of course, `db-server` should be _your_ db-server hostname.

**Comment by Abdelrahman1985** [comment]
also now my inventory file in
/etc/ansible/hosts/inventory.dev should be as the following ?
[ldap-servers]
ldap.asrenorg.net needs_certificate=true



[shibboleth-idps]
idp.asrenorg.net  needs_certificate=true



[science-gateways]
sgw.asrenorg.net needs_certificate=true



[db-servers]
min_jvm_size=1024m max_jvm_size=2048m db-server=sgw.asrenorg.net  needs_certificate="true"

[identity-all:children]
ldap-servers
shibboleth-idps
science-gateways
db-servers


[CentOS-servers:children]
identity-all

**Comment by brucellino** [comment]
Yes, this looks fine. However, note that the group  that you've specified your hosts to belong to (`identity-all`) has the following variables (in `group_vars/identity-all`) : 
```yaml
# institute metadata
site_name: Catch-All
host_institute:
  name: Africa-Arabia Regional Operations Centre
  url: http://aaroc.github.io

# LDAP variables
server_country: ZA
server_state:
server_location: Bloemfontein
server_organization: CSIR
server_organization_unit: SAGrid
organisation:
  name: SAGrid
  logo: csir_meraka.jpg
ldap_server: ldap.sagrid.ac.za
sgw_admin: brucellino@gmail.com
mail_contact: bbecker@csir.co.za
# IDP variables. these are specifically related to the IdPOpen Web front end.
idp:
  name: Catch-All Identity Provider
  admin_user: Bruce Becker
  admin_email: bbecker@csir.co.za
  metadata_url: https://{{ hostvars[groups['shibboleth-idps'][0]]['ansible_fqdn']}}/idp/shibboleth
  mail_server: smtp.google.com
  header_logo: Logo.jpg
```
You should copy `group_vars/identity-all` to something like `group_vars/identity-asren` to add your institute-specific information, and change your inventory to be : 

```
[ldap-servers]
ldap.asrenorg.net needs_certificate=true

[shibboleth-idps]
idp.asrenorg.net needs_certificate=true

[science-gateways]
sgw.asrenorg.net needs_certificate=true

[db-servers]
min_jvm_size=1024m max_jvm_size=2048m db-server=sgw.asrenorg.net needs_certificate="true"

[identity-asren:children]
ldap-servers
shibboleth-idps
science-gateways
db-servers

[CentOS-servers:children]
identity-asren
```
