### ISSUE TITLE
 A vault password must be specified to decrypt.

### ISSUE THREAD

**Issue by qasims** [AAROC/DevOps#238]
When I run following command I get error. I already specified vault password file exist in group_vars created by ansible-vault command still it giving error.

```
ansible-playbook -k /etc/ansible/idp-ldap.yml -u root -vvvv
SSH password:
ERROR: A vault password must be specified to decrypt /etc/ansible/group_vars/passwords-ssa.yml

```
Below is idp-ldap.yml
```
---
- name: Configure the LDAP machine
  hosts: ldap-servers
  remote_user: qasim
  sudo: true
  roles:
  - ldap
  vars_files:
    - "group_vars/passwords-ssa.yml"

- name: Prepare the identity machine common environment
  hosts: shibboleth-idps
  remote_user: qasim
  sudo: true
  roles:
  - fmarco76.tomcat
  - shibboleth-idp
  - fmarco76.IDPPublic
  post_tasks:
    - name: Announce new IdP to the federation manager
      action:
        module: slack
        domain: idp-se-ampr-org.slack.com
        token: T06TL7V17/B06U0LDBK/2WFsmJFsNf2vEgelD8yBWh4w
        msg: "A new Shib-IdP has been deployed. Metadata is at {{ idp.metadata_$
        channel: "#ssaidp"
        username: "Ansible on {{ ansible_fqdn }}"
        link_names: 1
        parse: 'full'

```
