### ISSUE TITLE
Add a test to see whether superuser is already in the LDAP directory

### ISSUE THREAD

**Issue by brucellino** [AAROC/DevOps#27]
The LDAP directory has a superuser, which is added and configured by the ldap role.

We need to add a conditional to only perform this when the user is not already present.

```
- name: Create the root user
  user: ansible
  sudo: True
  command: 
# when: root user is not already in the tree
```
